GET http://localhost:5085/

###
GET http://localhost:5085/hellous


//( when starting from bin/debug/net9.0 port is 5000 for some reason)

###
GET http://localhost:5000/hellous
```

###
GET http://localhost:5085/hellous
```

###
GET  http://my-very-best-net24s-chapp.azurewebsites.net/



// az webapp config appsettings set --name my-very-best-net24s-chapp --resource-group test1 --settings APPINSIGHTS_INSTRUMENTATIONKEY=$(az monitor app-insights component show --app myappinsights --resource-group test1 --query instrumentationKey -o tsv) APPLICATIONINSIGHTS_CONNECTION_STRING=$(az monitor app-insights component show --app myappinsights --resource-group test1 --query connectionString -o tsv) ApplicationInsightsAgent_EXTENSION_VERSION=~3

